name: NodeJS with Rollup

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/

    - name: Build
      run: |
        npm install
        npm install rollup@0.67.4 -g
        tsc --project tsconfig.build.json
        rollup -c rollup.config.ts
        node build/browserify.js
        npm publish
      
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
